import express from "express";
import cors from "cors";
import dotenv from "dotenv";
dotenv.config();
import aiRoutes from "./route/ai.route.js";
import chatRoutes from "./route/chat.route.js";
import { HandleEdit } from "./controller/edit.controller.js";
import { HandleCode } from "./controller/code.controller.js";
import { register } from "./controller/register.controller.js";
import { login } from "./controller/login.controller.js";
import { Debug } from "./controller/debug.controller.js";
import { Upload } from "./controller/upload.controller.js";
export const app=express();
app.use(cors());
app.use(express.json());
app.use("/api/auth/register",register);
app.use("/api/auth/login",login);
app.use("/api/ai", aiRoutes);
app.use("/api/chats", chatRoutes);
app.use("/api/edit",HandleEdit);
app.use("/api/run-code",HandleCode);
app.use("/api/debug-code",Debug);
app.use("/api/upload",Upload);